# Stage 1: Download the dataset
FROM python:3.9 AS builder

# Update and install security patches
RUN apt-get update && apt-get upgrade -y && apt-get clean

# Install datasets library to download the data
RUN pip install --no-cache-dir datasets

COPY core/preprocess_dataset.py preprocess_dataset.py

# Download the dataset
RUN python preprocess_dataset.py

# Stage 2: Application
FROM python:3.9

# Update and install security patches
RUN apt-get update && apt-get upgrade -y && apt-get clean

WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the downloaded dataset from the builder stage
COPY --from=builder processed_dataset.pkl /data/processed_dataset.pkl

# Copy the application code
COPY . .

# Expose the port
EXPOSE 8000

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]